name: chatting_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0
  http: ^1.5.0
  rxdart: ^0.28.0
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner:
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

